# fly.toml file generated for ascend on 2022-07-01T11:07:56+01:00

app = "ascend"
kill_signal = "SIGTERM"
kill_timeout = 5
processes = []

# Not required with SQLite3 see Application.start
# [deploy]
#   release_command = "/app/bin/migrate"

[env]
  DATABASE_PATH="/data/ascend_data/ascend_prod.db"
  PHX_HOST = "ascend.fly.dev"
  PORT = "8080"

[experimental]
  allowed_public_ports = []
  auto_rollback = true

[mounts]
source="ascend_data"
destination="/data"

[[services]]
  http_checks = []
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"
  script_checks = []
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"
